openapi: 3.1.0
info:
  title: business-matching-app
  version: '1.0'
  summary: ''
  description: Business Matching App Company APIs
servers:
  - url: 'http://localhost:8080'
paths:
  /companies/validateSignUp:
    post:
      summary: Company Validate SignUp
      responses:
        '200':
          $ref: '#/components/responses/CompanySignUpResponse'
        '400':
          $ref: '#/components/responses/CompanySignUpResponse'
        '500':
          $ref: '#/components/responses/InternalServerErrorResponse'
      operationId: post-auth-validate_sign_up
      requestBody:
        $ref: '#/components/requestBodies/CompanySignUpInput'
      description: validate sign up
  /companies/signUp:
    post:
      summary: Company SignUp
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/CompanySignUpResponse'
        '400':
          $ref: '#/components/responses/CompanySignUpResponse'
        '500':
          $ref: '#/components/responses/InternalServerErrorResponse'
      operationId: post-auth-sign_up
      requestBody:
        $ref: '#/components/requestBodies/CompanySignUpInput'
  /companies/signIn:
    post:
      summary: Company Sign In
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/CompanySignInOkResponse'
        '400':
          $ref: '#/components/responses/CompanySignInBadRequestResponse'
        '500':
          $ref: '#/components/responses/InternalServerErrorResponse'
      operationId: post-auth-sign_in
      requestBody:
        $ref: '#/components/requestBodies/CompanySignInInput'
components:
  schemas:
    CompanySignUpValidationError:
      title: CompanySignUpValidationError
      type: object
      properties:
        name:
          type: array
          items:
            type: string
        tel:
          type: array
          items:
            type: string
        email:
          type: array
          items:
            type: string
        password:
          type: array
          items:
            type: string
  requestBodies:
    CompanySignUpInput:
      content:
        application/json:
          schema:
            type: object
            required:
              - name
              - tel
              - email
              - password
            properties:
              name:
                type: string
              tel:
                type: string
              email:
                type: string
              password:
                type: string
      description: SignUp Company Iuput
    CompanySignInInput:
      content:
        application/json:
          schema:
            type: object
            required:
              - email
              - password
            properties:
              email:
                type: string
              password:
                type: string
      description: SignIn Company Input
  responses:
    CompanySignUpResponse:
      description: ''
      content:
        application/json:
          schema:
            type: object
            required:
              - code
              - errors
            properties:
              code:
                type: integer
                format: int64
              errors:
                type: object
                $ref: '#/components/schemas/CompanySignUpValidationError'
    CompanySignInOkResponse:
      description: Company SignIn Response
      content:
        application/json:
          schema:
            type: object
      headers:
        Set-Cookie:
          schema:
            type: string
    CompanySignInBadRequestResponse:
      description: Company SignIn BadRequest Response
      content:
        application/json:
          schema:
            type: object
            required:
              - errors
            properties:
              errors:
                type: array
                items:
                  type: string
    InternalServerErrorResponse:
      description: Internal Server Error Response
      content:
        application/json:
          schema:
            type: object
            required:
              - code
              - message
            properties:
              code:
                type: integer
                format: int64
              message:
                type: string
tags:
  - name: companies
    description: companies end point
  - name: business matching app
    description: business matching app
