version: '3.9'
services:
  registration-frontend:
    build: ./frontend
    volumes:
      - ./frontend/:/src
      # - ./api_server/app/swagger:/src/swagger
    ports:
      - 5173:5173
      - 6006:6006
    networks:
      - container-link
    tty: true
    stdin_open: true

networks:
  container-link:
    name: business-matching-local-network
    external: true
