openapi: 3.1.0
x-stoplight:
  id: 612ou0h114gjn
info:
  title: business-matching-app
  version: '1.0'
  summary: ''
  description: Business Matching App APIs
servers:
  - url: http://localhost:8080
paths:
  /auth/validate_supporter_sign_up:
    post:
      summary: Validate SignUp
      responses:
        '200':
          $ref: '#/components/responses/SupporterSignUpResponse'
        '400':
          $ref: '#/components/responses/SupporterSignUpResponse'
      operationId: post-auth-validate_sign_up
      x-stoplight:
        id: u7cygk8xkvvgg
      requestBody:
        $ref: '#/components/schemas/SupporterSignUpInput'
      description: validate sign up
      tags:
        - auth
components:
  schemas: {}
  requestBodies:
    SupporterSignUpInput:
      description: Supporter Sign Up Iuput
      content:
        application/json:
          schema:
            type: object
            required:
              - firstName
              - lastName
              - email
              - password
            properties:
              firstName:
                type: string
                x-stoplight:
                  id: 8az2jxi080ws4
              lastName:
                type: string
                x-stoplight:
                  id: 7gs5gq1qxvpjd
              email:
                type: string
                x-stoplight:
                  id: 1yke3wsrbxprw
              password:
                type: string
                x-stoplight:
                  id: pvuvapq91veqr
              birthday:
                type: string
                x-stoplight:
                  id: xarue11e8g226
              frontIdentification:
                type: string
                x-stoplight:
                  id: z5o24dk1i6sof
                format: binary
              backIdentification:
                type: string
                x-stoplight:
                  id: t4r1u2yt9xz06
                format: binary
              skills:
                type: array
                x-stoplight:
                  id: b69djiw1eztck
                items:
                  x-stoplight:
                    id: e6oo9666kcggq
                  type: integer
                  format: int64
  responses:
    SupporterSignUpResponse:
      description: ''
      content:
        application/json:
          schema:
            type: object
            required:
              - code
              - errors
            properties:
              code:
                type: integer
                x-stoplight:
                  id: n7as40fslzhm5
                format: int64
              errors:
                type: object
                x-stoplight:
                  id: zfqo4lkomvywz
                properties:
                  firstName:
                    type: array
                    x-stoplight:
                      id: wgxeu79bndqxu
                    items:
                      x-stoplight:
                        id: wmmhy155k7swz
                      type: string
                  lastName:
                    type: array
                    x-stoplight:
                      id: gggmj9r8z2a1a
                    items:
                      x-stoplight:
                        id: x6qitjjrzql0o
                      type: string
                  email:
                    type: array
                    x-stoplight:
                      id: rf219qqlo08h2
                    items:
                      x-stoplight:
                        id: 78xapiqhrh2f4
                      type: string
                  password:
                    type: array
                    x-stoplight:
                      id: n77gcy98fjfyt
                    items:
                      x-stoplight:
                        id: ddl66eid68u0p
                      type: string
                  frontIdentification:
                    type: array
                    x-stoplight:
                      id: 35zvebdn9a2dj
                    items:
                      x-stoplight:
                        id: 6iqyx9v7x0rrf
                      type: string
                  backIdenfitication:
                    type: array
                    x-stoplight:
                      id: pqjrite4wie6g
                    items:
                      x-stoplight:
                        id: 38bputcx5jpjk
                      type: string
                  skills:
                    type: array
                    x-stoplight:
                      id: gkk4wdmmk7sa7
                    items:
                      x-stoplight:
                        id: p5ebykfd8sk9n
                      type: string
tags:
  - name: auth
    description: auth endpoint
  - name: business matching app
    description: business matching app
